/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TodoId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PersistedTodo = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTodo' : IDL.Func([IDL.Text], [TodoId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCompleted' : IDL.Func([], [], []),
  'completeAll' : IDL.Func([], [], []),
  'delete' : IDL.Func([TodoId], [], []),
  'deleteAllTodos' : IDL.Func([], [], []),
  'getActiveTodos' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TodoId, PersistedTodo))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedTodos' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TodoId, PersistedTodo))],
      ['query'],
    ),
  'getTodos' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TodoId, PersistedTodo))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggle' : IDL.Func([TodoId], [], []),
  'toggleAll' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TodoId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PersistedTodo = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTodo' : IDL.Func([IDL.Text], [TodoId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCompleted' : IDL.Func([], [], []),
    'completeAll' : IDL.Func([], [], []),
    'delete' : IDL.Func([TodoId], [], []),
    'deleteAllTodos' : IDL.Func([], [], []),
    'getActiveTodos' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TodoId, PersistedTodo))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedTodos' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TodoId, PersistedTodo))],
        ['query'],
      ),
    'getTodos' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TodoId, PersistedTodo))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggle' : IDL.Func([TodoId], [], []),
    'toggleAll' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };